import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { AppScreen, BrandMark, Card, PageTitle, PrimaryButton } from "@/components/ui";
import { colors } from "@/src/theme";
import { useApp } from "@/src/store";

export default function ProfileScreen() {
  const { user, logout, resetDemoData } = useApp();
  const logoutNow = () => { logout(); router.replace("/login"); };
  const reset = () => Alert.alert("Demo verilerini sıfırla", "Cihazdaki ek kayıtlar silinip sunum verileri geri yüklenecek.", [{ text: "Vazgeç", style: "cancel" }, { text: "Sıfırla", style: "destructive", onPress: resetDemoData }]);
  return <AppScreen><BrandMark compact/><PageTitle eyebrow="HESAP VE AYARLAR" title="Profil" description="Cihaz oturumu ve yerel demo verilerini yönetin."/><Card style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>{user?.name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</Text></View><Text style={styles.name}>{user?.name}</Text><Text style={styles.email}>{user?.email}</Text><View style={styles.role}><Ionicons name="shield-checkmark" size={15} color={colors.primary}/><Text style={styles.roleText}>Yönetici • Demo oturumu</Text></View></Card><Card style={{ gap: 4 }}><Setting icon="cloud-offline-outline" title="Yerel veri modu" caption="Kayıtlar bu cihazda saklanır"/><Setting icon="phone-portrait-outline" title="Expo Go geliştirme sürümü" caption="App Store veya TestFlight gerekmez"/><Setting icon="information-circle-outline" title="AfetSaha V3.0" caption="Eğitim ve karar destek uygulaması"/></Card><Pressable onPress={reset} style={styles.reset}><Ionicons name="refresh-outline" size={19} color={colors.red}/><View style={{ flex: 1 }}><Text style={styles.resetTitle}>Demo verilerini sıfırla</Text><Text style={styles.resetText}>Hazır sunum kayıtlarını geri yükle</Text></View></Pressable><PrimaryButton secondary icon="log-out-outline" title="Oturumu kapat" onPress={logoutNow}/><Text style={styles.disclaimer}>Tıbbi teşhis yerine geçmez. Nihai değerlendirme yetkili sağlık personeline aittir.</Text></AppScreen>;
}

function Setting({ icon, title, caption }: { icon: keyof typeof Ionicons.glyphMap; title: string; caption: string }) { return <View style={styles.setting}><View style={styles.settingIcon}><Ionicons name={icon} size={19} color={colors.primary}/></View><View style={{ flex: 1 }}><Text style={styles.settingTitle}>{title}</Text><Text style={styles.settingCaption}>{caption}</Text></View></View>; }

const styles = StyleSheet.create({ profile: { alignItems: "center", paddingVertical: 25 }, avatar: { width: 76, height: 76, borderRadius: 25, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center" }, avatarText: { color: colors.primaryDark, fontSize: 24, fontWeight: "800" }, name: { color: colors.text, fontSize: 20, fontWeight: "800", marginTop: 13 }, email: { color: colors.textMuted, fontSize: 12, marginTop: 4 }, role: { flexDirection: "row", alignItems: "center", gap: 6, backgroundColor: colors.primarySoft, borderRadius: 99, paddingHorizontal: 11, minHeight: 30, marginTop: 13 }, roleText: { color: colors.primaryDark, fontSize: 11, fontWeight: "700" }, setting: { minHeight: 68, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: 1, borderBottomColor: colors.border }, settingIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center" }, settingTitle: { color: colors.text, fontSize: 13, fontWeight: "700" }, settingCaption: { color: colors.textMuted, fontSize: 10, marginTop: 4 }, reset: { minHeight: 68, flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 15, borderRadius: 18, borderWidth: 1, borderColor: "#F1D9DD", backgroundColor: colors.redSoft }, resetTitle: { color: colors.red, fontSize: 13, fontWeight: "700" }, resetText: { color: colors.textMuted, fontSize: 10, marginTop: 4 }, disclaimer: { color: colors.textMuted, fontSize: 10, lineHeight: 16, textAlign: "center", paddingHorizontal: 18 } });
